---
project_name: itervar

release:
  github:
    owner: p1ass
    name: itervar

builds:
  - binary: itervar
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
    main: ./cmd/itervar/

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - 'README'
      - Merge pull request
      - Merge branch
